### ISSUE TITLE
product type error

### ISSUE THREAD

**Issue by VietAnhDao** [kewlbear/Open3D-iOS#31]
I've got a product type error when attempting to run the example app with: 

"unable to resolve product type 'com.apple.product-type.tool' for platform 'iphonesimulator'"

And similarly when I try to add the packages to my app. Any ideas on what is causing this? and can I ask if any apps made with Open3D-iOS and PythonKit be published to iOS App Store.

Thanks,
Viet

**Comment by kewlbear** [comment]
This error occurs when you try to compile command line apps for iOS because iOS doesn't support command line apps.  I don't think my example app will produce such an error.  Did you change something?  I don't know exactly which apps are built with those packages and published on AppStore, but I assume based on activities/traffic on GitHub there should be some.

**Comment by VietAnhDao** [comment]
Hi, thank you for the reply and what an exciting time with python working inside swift and iOS! . 

Not sure of the exact issue was but if I get PythonKit from pvieito's repo the problem goes away.
